apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: admin-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-server
  strategy: {}
  template:
    metadata:
     
      labels:
        app: admin-server
    spec:
      containers:
        - image: 390665570631.dkr.ecr.eu-west-1.amazonaws.com/thich48-repo/petclinic-app-dev:admin-server-v2.1.2-b109
          name: admin-server
          ports:
            - containerPort: 9090
          
