apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  labels:
    app: mydeployment
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  selector:
    app: mydeployment